version: '3'

services:

  postgres:
    image: postgres:15.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "wikiseer", "-U", "writer" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_DB=wikiseer
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./wiki-seer-db/sql:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3

  wikiseerdata:
    image: localhost:5000/wikiseerdata
    build:
      context: "wiki-seer-data"
    environment:
      - DB_USER=writer
      - DB_PASSWORD=writer
      - DB_NAME=wikiseer
    depends_on:
      postgres:
        condition: service_healthy

  wikiseertrain:
    image: localhost:5000/wikiseertrain
    build:
      context: "wiki-seer-train"
    environment:
      - DB_USER=reader
      - DB_PASSWORD=reader
      - DB_NAME=wikiseer
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy

  wikiseerapi:
    image: localhost:5000/wikiseerapi
    healthcheck:
        test: [ "CMD", "curl", "-f", "http://wikiseerapi:8000/ruok"]
        timeout: 45s
        interval: 10s
        retries: 10
    build:
      context: "wiki-seer-api"
    environment:
      - DB_USER=reader
      - DB_PASSWORD=reader
      - DB_NAME=wikiseer
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"

  wikiseerui:
    image: localhost:5000/wikiseerui
    healthcheck:
        test: [ "CMD", "curl", "-f", "http://wikiseerui:8001/ruok"]
        timeout: 45s
        interval: 10s
        retries: 10
    build:
      context: "wiki-seer-ui"
    depends_on:
      wikiseerapi:
        condition: service_healthy
    ports:
      - "8001:8001"
